name: Continous Integration and Testing

on:
  push:
    branches: "main"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
      # env:
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # MYSQL_DATABASE: laravel
      # ports:
      #  - 33306:3306
      #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3
      #- name: Copy .env
      #run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Config Clearing
        run: php artisan config:clear

      - name: Cache Clearing
        run: php artisan cache:clear

      - name: Route Clearing
        run: php artisan route:clear

      - name: Route Clearing
        run: php artisan optimize:clear

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Clear Config
        run: php artisan config:clear
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install npm Dependencies
        run: npm install
      - name: Build React App
        run: npm run build
        
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.gridape.com
          username: beta@beta.gridape.com
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
